backend:
  name: git-gateway
  branch: main

# publish_mode: editorial_workflow
media_folder: "assets/images/posts" # Media files will be stored in the repo under src/assets/images/posts
public_folder: "/assets/images/posts" # The src attribute for uploaded media will begin with assets/images/posts

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/blogs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false # Disable the editor preview and use instead 'preview links'
    fields: # The fields for each document, usually in front matter
      - { name: "title", label: "Title" }
      - { label: "Image", name: "image", widget: "image" }
      - { name: "description", label: "Description" }
      - { name: "autor", label: "Autor" }
      - { name: "correo", label: "Correo" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
      - {
          name: "highlight",
          label: "Highlight",
          widget: "boolean",
          default: false,
          hint: "Display posts in home's highlights",
        }
  - name: "eventos" # Used in routes, e.g., /admin/collections/blog
    label: "Eventos" # Used in the UI
    folder: "src/eventos" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false # Disable the editor preview and use instead 'preview links'
    fields: # The fields for each document, usually in front matter
      - { name: "title", label: "Title" }
      - { label: "Image", name: "image", widget: "image" }
      - { name: "description", label: "Description" }
      - { name: "autor", label: "Autor" }
      - { name: "correo", label: "Correo" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
      - {
          name: "highlight",
          label: "Highlight",
          widget: "boolean",
          default: false,
          hint: "Display posts in home's highlights",
        }
  - name: "podcast" # Used in routes, e.g., /admin/collections/podcast
    label: "Podcast" # Used in the UI
    folder: "src/podcasts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false # Disable the editor preview and use instead 'preview links'
    fields: # The fields for each document, usually in front matter
      - { name: "title", label: "Title" }
      - { name: "description", label: "Description" }
      - { name: "link", label: "Enlace de podcast" }
      - { name: "date", label: "Date", widget: "datetime" }
      - {
          name: "highlight",
          label: "Highlight",
          widget: "boolean",
          default: false,
          hint: "Display podcast in home's highlights",
        }
  - name: "gobcentral" # Used in routes, e.g., /admin/collections/podcast
    label: "Gobierno Central" # Used in the UI
    folder: "src/gobcentral" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false # Disable the editor preview and use instead 'preview links'
    fields: # The fields for each document, usually in front matter
      - { name: "title", label: "Title" }
      - { name: "ano", label: "Año" }
      - { name: "slider", label: "slider", widget: "image" }
      - { name: "resumen1", label: "Resumen Aprobado" }
      - { name: "resumen2", label: "Resumen Ejecutado" }
      - { name: "resumen3", label: "Resumen Porcentaje" }
      - { name: "grafica", label: "Gráfica Ejecucion", widget: "markdown" }
      - {
          name: "fechaactualizaciong",
          label: "Fecha de Actualización de Gráfica",
          widget: "date",
        }
      - { name: "tabla", label: "Tabla Ejecución", widget: "markdown" }
      - {
          name: "fechaactualizaciont",
          label: "Fecha de Actualización de Tabla",
          widget: "date",
        }
      - {
          name: "highlight",
          label: "Highlight",
          widget: "boolean",
          default: false,
          hint: "Display posts in home's highlights",
        }
  - name: "municipal" # Used in routes, e.g., /admin/collections/podcast
    label: "Municipal" # Used in the UI
    folder: "src/municipal" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false # Disable the editor preview and use instead 'preview links'
    fields: # The fields for each document, usually in front matter
      - { name: "title", label: "Title" }
      - { name: "ano", label: "Año" }
      - { name: "slider", label: "slider", widget: "image" }
      - { name: "resumen1", label: "Resumen Aprobado" }
      - { name: "resumen2", label: "Resumen Ejecutado" }
      - { name: "resumen3", label: "Resumen Porcentaje" }
      - { name: "grafica", label: "Gráfica Ejecucion", widget: "markdown" }
      - {
          name: "fechaactualizaciong",
          label: "Fecha de Actualización de Gráfica",
          widget: "date",
        }
      - { name: "tabla", label: "Tabla Ejecución", widget: "markdown" }
      - {
          name: "fechaactualizaciont",
          label: "Fecha de Actualización de Tabla",
          widget: "date",
        }
      - {
          name: "highlight",
          label: "Highlight",
          widget: "boolean",
          default: false,
          hint: "Display posts in home's highlights",
        }
  - name: "obraspublicas" # Used in routes, e.g., /admin/collections/podcast
    label: "Obras Públicas" # Used in the UI
    folder: "src/obraspublicas" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false # Disable the editor preview and use instead 'preview links'
    fields: # The fields for each document, usually in front matter
      - { name: "title", label: "Title" }
      - { name: "ano", label: "Año" }
      - { name: "slider", label: "slider", widget: "image" }
      - { name: "resumen1", label: "Resumen Aprobado" }
      - { name: "resumen2", label: "Resumen Ejecutado" }
      - { name: "resumen3", label: "Resumen Porcentaje" }
      - { name: "grafica", label: "Gráfica Ejecucion", widget: "markdown" }
      - {
          name: "fechaactualizaciong",
          label: "Fecha de Actualización de Gráfica",
          widget: "date",
        }
      - { name: "tabla", label: "Tabla Ejecución", widget: "markdown" }
      - {
          name: "fechaactualizaciont",
          label: "Fecha de Actualización de Tabla",
          widget: "date",
        }
      - {
          name: "highlight",
          label: "Highlight",
          widget: "boolean",
          default: false,
          hint: "Display posts in home's highlights",
        }
  - name: "contratacionespublicas" # Used in routes, e.g., /admin/collections/podcast
    label: "Contrataciones Públicas" # Used in the UI
    folder: "src/contratacionespublicas" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false # Disable the editor preview and use instead 'preview links'
    fields: # The fields for each document, usually in front matter
      - { name: "title", label: "Title" }
      - { name: "ano", label: "Año" }
      - { name: "slider", label: "slider", widget: "image" }
      - { name: "resumen1", label: "Resumen Aprobado" }
      - { name: "resumen2", label: "Resumen Ejecutado" }
      - { name: "resumen3", label: "Resumen Porcentaje" }
      - { name: "grafica", label: "Gráfica Ejecucion", widget: "markdown" }
      - {
          name: "fechaactualizaciong",
          label: "Fecha de Actualización de Gráfica",
          widget: "date",
        }
      - { name: "tabla", label: "Tabla Ejecución", widget: "markdown" }
      - {
          name: "fechaactualizaciont",
          label: "Fecha de Actualización de Tabla",
          widget: "date",
        }
      - {
          name: "highlight",
          label: "Highlight",
          widget: "boolean",
          default: false,
          hint: "Display posts in home's highlights",
        }

show_preview_links: true
